name: pionex-csv-to-cointracker-csv
recipe: lemp
config:
  webroot: .
  xdebug: debug

services:
  appserver:
      environment:
        # Support debugging with XDEBUG 3.
        XDEBUG_MODE:
        # Support debugging Drush with XDEBUG 3.
        PHP_IDE_CONFIG: "serverName=appserver"

tooling:
  # Example: lando build
  convert:
    service: appserver
    description: "Execute example.php to convert trading.csv and deposit-withdraw.csv to cointracracker.csv."
    cmd: php -f example.php
  xdebug:
    description: Loads Xdebug in the selected mode
    cmd:
      - appserver: /app/.lando/tooling-xdebug.sh
    user: root
