name: pionex-csv-to-cointracker-csv
recipe: lemp
config:
  webroot: .
  xdebug: debug

services:
  appserver:
      environment:
        # Support debugging with XDEBUG 3.
        XDEBUG_MODE:
        # Support debugging Drush with XDEBUG 3.
        PHP_IDE_CONFIG: "serverName=appserver"

tooling:
  # Make build-common-repo.sh available through Lando.
  # Example: lando build
  convert:
    service: appserver
    description: "Run build-common-repo.sh"
    cmd: php -f pionex_csv_to_cointracker_csv.php
  xdebug:
    description: Loads Xdebug in the selected mode
    cmd:
      - appserver: /app/.lando/tooling-xdebug.sh
    user: root
